spring.application.name=oo

db.host=localhost
db.port=5432
db.name=bdoo
db.user=admbdoo
db.password=123456

dbadm.host=localhost
dbadm.port=5432
dbadm.name=postgres
dbadm.user=admbdoo
dbadm.password=123456
