spring.application.name=oo

db.host=localhost
db.port=5432
db.name=bdoo
db.user=postgres
db.password=postgres

dbadm.host=localhost
dbadm.port=5432
dbadm.name=postgres
dbadm.user=postgres
dbadm.password=postgres
